[build]
  base = ""
  command = "yarn docs:build"
  publish = "docs/.vuepress/dist"

[[redirects]]
  from = "/docs/"
  to = "/getting-started/macos/"
  status = 302
  force = true

[[redirects]]
  from = "/docs/getting-started/"
  to = "/getting-started/macos/"
  status = 302
  force = true

[[redirects]]
  from = "/docs/bedrock/"
  to = "/bedrock/master/installation/"
  status = 302
  force = true

[[redirects]]
  from = "/docs/trellis/"
  to = "/trellis/master/installation/"
  status = 302
  force = true

[[redirects]]
  from = "/docs/sage/"
  to = "/sage/10.x/installation/"
  status = 302
  force = true

[[redirects]]
  from = "/docs/sage/9.x/"
  to = "/sage/9.x/installation/"
  status = 302
  force = true

[[redirects]]
  from = "/docs/sage/8.x/"
  to = "/sage/8.x/installation/"
  status = 302
  force = true

[[redirects]]
  from = "/docs/examples/"
  to = "/examples/roots-example-project/"
  status = 302
  force = true
